version: "3"

services:
  mongo:
    image: mongo:5
    restart: unless-stopped
    environment:
      MONGO_DATABASE: "coderhouse"
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"